"""
Lightweight remediation assistance.

Generates env-var-based code suggestions, a .env.example snippet, and a
readable remediation patch — WITHOUT requiring repo write access or opening
pull requests. The output is meant to give an engineer a concrete starting
point, not a guaranteed auto-apply.
"""

import re
from pathlib import Path

# Well-known secret types map to conventional env var names.
_ENV_VAR_MAP = {
    "AWS Access Key": "AWS_ACCESS_KEY_ID",
    "AWS Secret Access Key": "AWS_SECRET_ACCESS_KEY",
    "GitHub Personal Access Token": "GITHUB_TOKEN",
    "GitHub OAuth Token": "GITHUB_OAUTH_TOKEN",
    "GitHub App Token": "GITHUB_APP_TOKEN",
    "Google API Key": "GOOGLE_API_KEY",
    "GCP Service Account Key": "GOOGLE_APPLICATION_CREDENTIALS",
    "Stripe Live Secret Key": "STRIPE_SECRET_KEY",
    "Stripe Test Secret Key": "STRIPE_TEST_SECRET_KEY",
    "Slack Bot Token": "SLACK_BOT_TOKEN",
    "Slack App Token": "SLACK_APP_TOKEN",
    "Twilio API Key": "TWILIO_API_KEY",
    "SendGrid API Key": "SENDGRID_API_KEY",
    "Private SSH Key": "SSH_PRIVATE_KEY",
    "PGP Private Key": "PGP_PRIVATE_KEY",
    "JWT Token": "JWT_TOKEN",
    "Database Connection String": "DATABASE_URL",
    "Generic API Key": "API_KEY",
    "Generic Secret": "APP_SECRET",
    "Hardcoded Password": "APP_PASSWORD",
    "Azure Storage Key": "AZURE_STORAGE_KEY",
    "Azure SAS Token": "AZURE_SAS_TOKEN",
    "npm Auth Token": "NPM_TOKEN",
    "PyPI API Token": "PYPI_TOKEN",
    "Discord Bot Token": "DISCORD_BOT_TOKEN",
    "Mailgun API Key": "MAILGUN_API_KEY",
}

_IDENT_RE = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9_\-\.]*)\s*[:=]")


def env_var_name(secret_type: str, context: str) -> str:
    """Derive an env var name, preferring the original identifier when present."""
    m = _IDENT_RE.match(context or "")
    if m:
        ident = re.sub(r"[^A-Za-z0-9]", "_", m.group(1)).upper().strip("_")
        if ident and not ident.isdigit():
            return ident
    return _ENV_VAR_MAP.get(secret_type, "SECRET_VALUE")


def _lang(file_path: str) -> str:
    ext = Path(file_path).suffix.lower()
    if ext == ".py":
        return "python"
    if ext in {".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs"}:
        return "node"
    if ext in {".rb"}:
        return "ruby"
    if ext in {".go"}:
        return "go"
    if ext in {".php"}:
        return "php"
    if file_path.split("/")[-1].startswith(".env") or ext in {".env"}:
        return "env"
    return "generic"


def suggest_replacement(file_path: str, context: str, env_var: str) -> str:
    """Produce the suggested replacement line for a finding's context."""
    lang = _lang(file_path)
    ident_match = _IDENT_RE.match(context or "")
    ident = ident_match.group(1) if ident_match else env_var.lower()

    if lang == "python":
        return f'{ident} = os.getenv("{env_var}")'
    if lang == "node":
        return f"const {ident} = process.env.{env_var}"
    if lang == "ruby":
        return f'{ident} = ENV["{env_var}"]'
    if lang == "go":
        return f'{ident} := os.Getenv("{env_var}")'
    if lang == "php":
        return f"${ident} = getenv('{env_var}');"
    if lang == "env":
        return f"{env_var}=${{{env_var}}}"
    return f'{ident} = <load "{env_var}" from environment>'


def build_remediation(scan, findings: list) -> dict:
    """Return a structured remediation report (JSON-serialisable)."""
    items = []
    env_lines: dict[str, str] = {}
    for f in findings:
        ev = env_var_name(f.secret_type, f.context)
        items.append({
            "file_path": f.file_path,
            "line_number": f.line_number,
            "secret_type": f.secret_type,
            "severity": f.severity,
            "env_var": ev,
            "before": (f.context or "").strip(),
            "after": suggest_replacement(f.file_path, f.context, ev),
            "guidance": f.remediation,
        })
        env_lines.setdefault(ev, f"{ev}=your_{ev.lower()}_here")

    env_example = "\n".join(
        ["# Generated by Automated Secrets Scanner", "# Move every secret below out of source code.", ""]
        + sorted(env_lines.values())
    ) + "\n"

    return {
        "scan_id": scan.id,
        "source_ref": scan.source_ref,
        "total_findings": len(findings),
        "next_steps": [
            "Rotate every exposed credential at its provider immediately.",
            "Move each secret into an environment variable or a secrets manager.",
            "Update deployment secrets (CI/CD, Render, Vercel, etc.).",
            "Add the relevant ignore rules (.env, *.pem) to .gitignore.",
            "Purge the secret from Git history if it was ever committed "
            "(git filter-repo or BFG Repo-Cleaner).",
        ],
        "env_example": env_example,
        "findings": items,
    }


def build_patch(scan, findings: list) -> str:
    """
    Build a readable, unified-diff-style remediation patch.

    Note: secrets are masked in storage, so this patch documents the intended
    change per location rather than guaranteeing a clean `git apply`. It gives
    engineers an exact, copy-pasteable before/after for each finding.
    """
    report = build_remediation(scan, findings)
    lines = [
        f"# Remediation patch for scan {scan.id[:8]}",
        f"# Source: {scan.source_ref}",
        f"# {len(findings)} finding(s). Review each hunk before applying — "
        "stored secrets are masked.",
        "",
    ]

    # Group by file for clean diff hunks.
    by_file: dict[str, list] = {}
    for item in report["findings"]:
        by_file.setdefault(item["file_path"], []).append(item)

    for file_path, items in by_file.items():
        lines.append(f"--- a/{file_path}")
        lines.append(f"+++ b/{file_path}")
        for it in sorted(items, key=lambda x: x["line_number"]):
            ln = it["line_number"]
            lines.append(f"@@ line {ln} — {it['secret_type']} ({it['severity']}) @@")
            lines.append(f"-{it['before']}")
            lines.append(f"+{it['after']}")
            lines.append("")

    lines.append("# ---- .env.example ----")
    lines.extend("# " + l for l in report["env_example"].splitlines())
    lines.append("")
    lines.append("# ---- Next steps ----")
    lines.extend(f"#  {i+1}. {s}" for i, s in enumerate(report["next_steps"]))
    lines.append("")
    return "\n".join(lines)
